### ISSUE TITLE
Failed to activate the lorem-ricksum package

### ISSUE THREAD

**Issue by Ryanspangenberg** [dane-johnson/lorem-ricksum-atom#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.14.6
**Thrown From**: [lorem-ricksum](https://github.com/dane-johnson/lorem-ricksum-atom) package 0.2.1

### Stack Trace

Failed to activate the lorem-ricksum package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1193727)
    at CompositeDisposable.add (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:1194695)
    at Object.consumeProvider (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:162421)
    at Object.consumeProvider_2 (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:162119)
    at Provider.provide (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1093694)
    at ServiceHub.provide (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3525828)
    at Package.activateServices (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3534167)
    at Package.activateNow (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3531143)
    at /Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3530467
    at Package.measure (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3528045)
    at /Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3530327
    at new Promise (<anonymous>)
    at Package.activate (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:3530270)
    at PackageManager.activatePackage (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:383646)
    at /Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:916751
    at r (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:911357)
    at s (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1121312)
    at ChildProcess.<anonymous> (/Users/Ryan/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:14:1121518)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -0:59.8.0 snippets:next-tab-stop (input.hidden-input)
     -0:59.8.0 snippets:expand (input.hidden-input)
     -0:59.8.0 editor:indent (input.hidden-input)
  8x -0:59.4.0 core:backspace (input.hidden-input)
     -0:57.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:57.5.0 snippets:expand (input.hidden-input)
     -0:57.5.0 editor:indent (input.hidden-input)
     -0:52.9.0 core:backspace (input.hidden-input)
     -0:52.1.0 snippets:next-tab-stop (input.hidden-input)
     -0:52.1.0 snippets:expand (input.hidden-input)
     -0:52.1.0 editor:indent (input.hidden-input)
     -0:51.5.0 editor:newline (input.hidden-input)
     -0:47.9.0 core:backspace (input.hidden-input)
     -0:47.6.0 snippets:next-tab-stop (input.hidden-input)
     -0:47.6.0 snippets:expand (input.hidden-input)
  7x -0:42.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.3.0 
highlight-selected 0.17.0 
lorem 4.0.0 
lorem-insults 0.2.0 
lorem-ricksum 0.2.1 
nc-gcode 0.2.0 
teletype 0.13.4 
```

**Comment by dane-johnson** [comment]
Aw jeez @solkaz somebody wants us to take responsibility for our busted CoffeeScript from our intern days.

**Comment by dane-johnson** [comment]
We gotta fix this Morty!
![image](https://user-images.githubusercontent.com/10768827/112193980-6ba26880-8bd6-11eb-9804-a8eea1444076.png)

**Comment by dane-johnson** [comment]
Jk 3b26b47 should fix it.
